#!/usr/bin/env bash

# GOAL: install pre requisites for the Tuffix installer
# AUTHOR: Jared Dyreson
# INSTITUTION: California State University Fullerton

cd /tmp
git clone "https://github.com/mshafae/tuffix.git"
cd tuffix/tool
sudo python3 setup.py install
