#!/usr/bin/env python3.8

import urllib.request as r
import os

print("[+] Downloading the zoom client.....")
url = "https://zoom.us/client/latest/zoom_amd64.deb"
file_path = os.path.basename(url)

r.urlretrieve(url, file_path)
print("[+] Saved zoom installer to {}".format(file_path))
os.system("stat {}".format(file_path))
