#!/usr/bin/env python3.8

# https://www.codespeedy.com/how-to-check-the-internet-connection-in-python/
# Found this code here and condensed it

import socket

def check():
    return (socket.gethostbyname(socket.gethostname()) != "127.0.0.1")

print("Connected!" if check() else "Not connected!")
