#!/usr/bin/env bash

# dictionaries in bash
# https://stackoverflow.com/questions/1494178/how-to-define-hash-tables-in-bash

declare -A codewords

codewords=(["cpsc-120"]="Introduction to C++" ["cpsc-121"]="Object Oriented Programming in C++" ["cpsc-131"]="Data Structures in C++")


function init() {
  # initialize tuffix
  # once installed, please create 
  # mark current user before sudo is invoked
  current_user="$USER"
  # create file /home/$current_user/.tuffix/.installed.lock
}

function add_codeword(){
  echo "hello"
}

function remove(){
  # remove a given Tuffix code word
  echo "remove"
}

function list_installed(){
  # list current Tuffix version
  # create file /home/$current_user/.tuffix/.installed_versions
  echo "list currently installed"
}

function list_available(){
  echo "list available"
}

function describe(){
  echo "describe"
}

function rekey(){
  echo "rekey"
}
