#!/usr/bin/env bash

# please also make sure the packages are exectuable before building the package, or do this during the postinst script

# dependencies for this script

[[ ! $(dpkg --list | grep "dpkg-dev") ]] && sudo apt-get install dpkg-dev -y

function build_(){
  base="tuffix-installer/"
  revision="$(awk '/Version:/ {print $2}' "$base"/DEBIAN/control | cut -d "-" -f1)"
  current_version="$(awk '/Version:/ {print $2}' "$base"/DEBIAN/control | cut -d "-" -f2)"
  new_version=$((current_version+1))
  arch="$(dpkg-architecture -qDEB_BUILD_ARCH)"
  package_name="tuffix_"$revision-$new_version"_$arch"
  sed -i "s/Version: .*/Version: $revision-$new_version/" "$base"/DEBIAN/control
  echo "[+] Building $package_name.deb"
  dpkg-deb --build "$base" "builds"/"$package_name".deb
}

function err_(){
  echo "please run on a debian machine"
  exit
}

[[ "$(uname -a | grep -i "ubuntu")" ]] && build_ || err_
