#!/usr/bin/env bash

# example debian build script we can use
# this took me less than 20 minutes to come up with
# https://askubuntu.com/questions/1130558/how-to-build-deb-package-for-ubuntu-18-04
# please also make sure the packages are exectuable before building the package, or do this during the postinst script

function build_(){
  base="tuffix-installer/"
  # copy all essenital files 
  cp -ar shell_scripts/hello  "$base"/usr/local/bin
  revision="$(awk '/Version:/ {print $2}' "$base"/DEBIAN/control | cut -d "-" -f1)"
  current_version="$(awk '/Version:/ {print $2}' "$base"/DEBIAN/control | cut -d "-" -f2)"
  new_version=$((current_version+1))
  package_name="com.csuf.tuffix_$revision-$new_version"
  sed -i "s/Version: .*/Version: $revision-$new_version/" "$base"/DEBIAN/control
  echo "$package_name".deb
  dpkg-deb --build "$base"
  dpkg -i tuffix_installer.deb
  dpkg --list | grep -i "tuffix"
}

function err_(){
  echo "please run on a debian machine"
  exit
}

#[[ "$(uname -a | grep -i "ubuntu")" ]] && build_ || err_
build_
