#!/usr/bin/env bash

# it seemed to be easier to use a shell script to write the logic of automatically updating the control file

function arg_err_(){
  echo "Usage: $0 [PKG_PATH]"
  exit
}

function dir_dne(){
  echo "[-] Cannot find $1, cowardly refusing!"
  exit
}

function aarch_err_(){
  echo "Please run on a debian machine, detected $(uname -r)"
  exit
}

#[[ -z "$@" ]] && arg_err_

#[[ "$(uname -a | grep -i "ubuntu")" ]] || aarch_err_

#[[ ! -d "$1" ]] && dir_dne

base="$1"
revision="$(awk '/Version:/ {print $2}' "$base"/DEBIAN/control | cut -d "-" -f1)"
current_version="$(awk '/Version:/ {print $2}' "$base"/DEBIAN/control | cut -d "-" -f2)"
new_version=$((current_version+1))
find "$base" -type f -not -path "*DEBIAN*" -exec chmod 755 {} \;

sed -i "s/Version: .*/Version: $revision-$new_version/" "$base"/DEBIAN/control
echo "[+] Updated tuffix-installer from version $current_version to $new_version"
