#####################################################################
# CPSC 223P
# point person: Michael Shafae
#####################################################################

- hosts: all
  remote_user: root
  tasks:

    - name: 223P Python environment
      apt:
        pkg:
          - python
          - python-dev
          - python-pip
          - python-virtualenv
          - python3
          - python3-dev
          - python3-pip
          - virtualenvwrapper

