#####################################################################
# CPSC 223J
# point person: Floyd Holliday
#####################################################################

- hosts: all
  remote_user: root
  tasks:

    - name: 223J Java environment
      apt:
        pkg:
          - geany
          - gthumb
          - netbeans
          - openjdk-8-jdk
          - openjdk-8-jre

