
#####################################################################
# Media Computation Tools
# point person:
#####################################################################

- hosts: all
  remote_user: root
  tasks:

    - name: media computation tools
      apt:
        pkg:
          - audacity
          - blender
          - gimp
          - imagemagick
          - sox
          - vlc

